Refactor variable names in install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -34,12 +34,13 @@ pushd "$install" > /dev/null
 dotdir="$(basename "$(pwd -L)")"
 
 install_links () {
-    local dot_subdir=${1}
-    local install_subdir=${2}
-    local install_dir=${3}
-    for path_entry in $(find "$dot_subdir" -mindepth 1 -maxdepth 1); do
-        local file_entry="$(basename "$path_entry")"
-        case "$file_entry" in
+    local dot_path=${1}
+    local install_path=${2}
+    local install_base_path=${3}
+    local dot_file=
+    for dot_file in $(find "$dot_path" -mindepth 1 -maxdepth 1 -printf %f\\n); do
+        local dot_full_path="$dot_path/$dot_file"
+        case "$dot_file" in
             .git) ;;
             .gitignore) ;;
             .gitmodules) ;;
@@ -50,41 +51,39 @@ install_links () {
             *~) ;;
             *.NO_INSTALL)
                 # create directories
-                local file_entry_real=${file_entry%.NO_INSTALL}
-                local file_entry_path="$install_subdir/$file_entry_real" # from dotdir to home to target path
-                local file="$(realpath -m -s --relative-to="$install_dir" "$file_entry_path")"
-                if [[ ! -e $file_entry_path ]]; then
-                    echo "mkdir     \"$file\""
-                    [[ -n $dry_run ]] || mkdir "$file_entry_path"
+                local install_file=${dot_file%.NO_INSTALL}
+                local install_full_path="$install_path/$install_file"
+                if [[ ! -e $install_full_path ]]; then
+                    echo "mkdir     $install_full_path"
+                    [[ -n $dry_run ]] || mkdir "$install_full_path"
                 fi
-                if [[ ! (-d $file_entry_path || (-n $dry_run && ! -e $file_entry_path)) || -L $file_entry_path ]]; then
-                    echo "error     \"$file\" not a directory"
+                if [[ ! (-d $install_full_path || (-n $dry_run && ! -e $install_full_path)) || -L $install_full_path ]]; then
+                    echo "error     $install_full_path not a directory"
                 else
-                    install_links "$dot_subdir/$file_entry" "$install_subdir/$file_entry_real" "$install_dir"
+                    install_links "$dot_full_path" "$install_full_path" "$install_base_path"
                 fi
                 ;;
             *)
                 # create links
-                link_dot_subdir="$dot_subdir/$file_entry"
-                local target="$(realpath -m -s --relative-to="$install_subdir" "$link_dot_subdir")"
-                link_install_subdir="$install_subdir/$file_entry"
-                local file="$(realpath -m -s --relative-to="$install_dir" "$link_install_subdir")"
-                if [[ -L $link_install_subdir && $(readlink "$link_install_subdir") == $target ]]; then
-                    echo "          \"$file\""
-                elif [[ -L $link_install_subdir && ! -e $link_install_subdir ]]; then # link without target
-                    echo "overwrite \"$file\" -> \"$target\""
-                    [[ -n $dry_run ]] || ln -sf "$target" "$link_install_subdir"
-                elif [[ -e $link_install_subdir ]]; then
-                    if ignore=$(diff "$link_install_subdir" "$link_dot_subdir"); then
-                        [[ -n $dry_run ]] || rm "$link_install_subdir"
-                        [[ -n $dry_run ]] || ln -s "$target" "$link_install_subdir"
-                        echo "replaced  \"$file\""
+                local install_file=$dot_file
+                local install_full_path="$install_path/$install_file"
+                local symlink_target="$(realpath -m -s --relative-to="$install_path" "$dot_full_path")"
+                if [[ -L $install_full_path && $(readlink "$install_full_path") == $symlink_target ]]; then
+                    echo "          $install_full_path"
+                elif [[ -L $install_full_path && ! -e $install_full_path ]]; then # link without target
+                    echo "overwrite $install_full_path -> $symlink_target"
+                    [[ -n $dry_run ]] || ln -sf "$symlink_target" "$install_full_path"
+                elif [[ -e $install_full_path ]]; then
+                    if ignore=$(diff "$install_full_path" "$dot_full_path"); then
+                        [[ -n $dry_run ]] || rm "$install_full_path"
+                        [[ -n $dry_run ]] || ln -s "$symlink_target" "$install_full_path"
+                        echo "replaced  $install_full_path"
                     else
-                        echo "skipped   \"$file\""
+                        echo "skipped   $install_full_path"
                     fi
                 else
-                    [[ -n $dry_run ]] || ln -s "$target" "$link_install_subdir"
-                    echo "installed \"$file\" -> \"$target\""
+                    [[ -n $dry_run ]] || ln -s "$symlink_target" "$install_full_path"
+                    echo "installed $install_full_path -> $symlink_target"
                 fi
                 ;;
         esac
